Attribute VB_Name = "Constantes"
' SPDX-License-Identifier: EUPL-1.2

' Pour forcer la déclaration de toutes les variables
Option Explicit

' constantes
Public Const ColumnOfSecondPartInCharge As Integer = 8
Public Const Label_Annees = "Année courante:"
Public Const Label_Autofinancement_Structure = "Autofinancmt structure"
Public Const Label_Autofinancement_Structure_Previous = "Autofinancmt structure années précédentes"
Public Const Label_Convention_Collective = "Convention collective: "
Public Const Label_Cout_J_Journalier = "Coût journalier"
Public Const Label_Cout_J_Salaire_Part_A = "A - Calcul des jours travaillables / an"
Public Const Label_Cout_J_Salaire_Part_B = "B/ Calcul Unité jours salaires "
Public Const Label_Cout_J_Salaire_Part_D = "Coût journée "
Public Const Label_NBConges = "Nb. Congés hors samedi:"
Public Const Label_NBRTT = "Nb. RTT:"
Public Const Label_NB_Jours_speciaux = "Nb. Jours non travaillés supplémentaires:"
Public Const Label_Pentecote = "Pentecôte = férié"
Public Const Label_Total_Financements = "Total des financements"
Public Const Label_Type_Financeur = "Type de financeur"
Public Const Label_Version As String = "Version du tableur:"
Public Const NBExtraCols As Integer = 6
Public Const NBCatOfCharges As Integer = 3
Public Const Nom_Feuille_Budget_chantiers As String = "Budget_chantiers"
Public Const Nom_Feuille_Budget_chantiers_realise As String = "Budget_chantiers_réalisé"
Public Const Nom_Feuille_Budget_global As String = "Budget_global"
Public Const Nom_Feuille_CC_by_SA As String = "CC BY SA V3.0"
Public Const Nom_Feuille_Charges = "Coût_j_chgs_indrctes"
Public Const Nom_Feuille_Cout_J_Salaire As String = "Coût_j_salaires"
Public Const Nom_Feuille_CptResult_prefix As String = "CptResult_"
Public Const Nom_Feuille_CptResult_Real_prefix As String = "CptResultReal_"
Public Const Nom_Feuille_CptResult_suffix As String = "Global"
Public Const Nom_Feuille_Eupl As String = "EUPL v1.2"
Public Const Nom_Feuille_FAQ As String = "FAQ"
Public Const Nom_Feuille_Informations As String = "Informations"
Public Const Nom_Feuille_Personnel As String = "Personnel"
Public Const Nom_Feuille_Versions As String = "Suivi des versions"
Public Const Offset_NB_Cols_For_Percent_In_CptResultReal As Integer = 9
Public Const T_Amout_Salary_of_WorkingPeople As String = "Masse salariale des %n%opérateurs : "
Public Const T_Charge As String = "la charge"
Public Const T_Create_CptResult_Formula As String = "Lister les chantiers à prendre en compte ;%n%séparés par des virgules ;%n%une série de chantier est indiquée par un tiret ;%n%Exemple ""1,4,6-8"" correspond aux chantiers 1, 4, 6, 7 et 8"
Public Const T_Create_CptResult_Formula_Title As String = "Choix des chantiers"
Public Const T_Create_Real_CptResult As String = "Faut-il créer un onglet ""Compte de résultat réalisé"" en plus du prévisionnel ?"
Public Const T_Create_Real_CptResult_Title As String = "Budget réel ?"
Public Const T_Get_CptResult_Suffix As String = "Quel suffixe pour le nom de l'onglet ?%n%Exemple : le suffixe %suffix% donne l'onglet %onglet%."
Public Const T_Get_CptResult_Suffix_Title As String = "Choix du suffixe"
Public Const T_Delete_Object_Of_Line As String = "Supprimer de %objectName% de la ligne ?"
Public Const T_Depense As String = "la dépense"
Public Const T_Error_Bad_Format_For_Charge_Name As String = "Erreur : les deux premiers caractères du nom doivent être compris entre 60 et 68 inclus."
Public Const T_Error_Existing_Tab_for_Suffix As String = "Erreur : le suffixe fourni (%suffix%) correspond déjà à un onglet existant."
Public Const T_Error_Formula_In_CptResult As String = "Erreur : la formule de la cellule %adr% n'est pas valide. Le calcul ne sera fait que pour le chantier 1."
Public Const T_Error_Incorrect_Formula As String = "Erreur : la formule fournie n'est pas correcte."
Public Const T_Error_Not_Empty_Charge_Name As String = "Erreur : Le nom fourni pour la charge ne peut pas être vide"
Public Const T_Error_Not_Possible_To_Associate_Line_To_Type As String = "Erreur : impossible d'associer cette ligne à un type de paiement (entre 60 et 68)"
Public Const T_Error_Not_Possible_To_Found_Type As String = "Erreur : impossible de retrouver les différents types de paiement (60 à 68)"
Public Const T_Financement As String = "le financement"
Public Const T_FirstName As String = "Prénom"
Public Const T_Formula As String = "Formule de choix des chantiers :"
Public Const T_Given_Line_Is_Not_Line_Of_Object As String = "La ligne entrée n'est pas la ligne d'%objectName%"
Public Const T_Line_To_Delete_For_Object As String = "Ligne %objectName% à supprimer"
Public Const T_NotFoundPage As String = "'%PageName%' n'a pas été trouvée"
Public Const T_NotFoundFirstName As String = "'Prénom' non trouvé dans '%PageName%' !"
Public Const T_Salary As String = "Rémunération des personnels"
Public Const T_Total_Charges As String = "Total Dépenses"
Public Const T_WorkingPeople As String = "Salarié"
